### ISSUE TITLE
Plus app problem backup won't

### ISSUE THREAD

**Issue by Wjxfi** [ammargitham/WallFlow#35] opened 2023-11-09 20:40 UTC
Hi, your app won't restore a backup from an app that has been updated from the lowest versions many times on android 12, miui 13.0.5, with app version 2.1.0, even though IN NORMAL VERSION IT RECOVERS (not reinstalled application}.

**Comment by ammargitham** [comment] 2023-11-15 10:44
@Wjxfi So backups from 2.1.0 regular don't work with 2.1.0 plus version?

Due to changes in schema, backups from later versions may not work in older versions. But I make sure that backups from older work on newer versions.

**Comment by ammargitham** [comment] 2023-11-19 07:54
I tried reproducing on my end but could not.

Is it possible for you to share the backup file which crashes? You can share it via email, if you don't want to upload it here.
If not, you could try getting the stacktrace using an app like [Scoop](https://f-droid.org/en/packages/taco.scoop/).

**Comment by ammargitham** [comment] 2023-11-20 11:39
I think this should be fixed by a recent commit: 5e6205f171f99c43badf158bb4f0930262e9d167. Will keep this open till you can verify it's fixed.

**Comment by ammargitham** [comment] 2023-11-30 13:59
Should be fixed in v2.2.0. Let me know if you still face this.

**Closed as completed** 2023-12-02 19:09 UTC
Labels: bug
