### ISSUE TITLE
[Bug] Modal bottom sheet dismiss causes app freeze

### ISSUE THREAD

**Issue by headquarter8302** [ammargitham/WallFlow#18] opened 2023-09-30 13:51 UTC
- Samsung Galaxy A04 on Android 13.
- IzzyOnDroid using F-Droid.
- Version 1.4.0

Whenever I try to close the drawer, the app simply freezes, and doesn't respond to any user input, and thus must be forcibly closed. Android however doesn't recognize it as being stuck, and just lets it do it's own thing

**Comment by ammargitham** [comment] 2023-09-30 14:12
If it's possible, could you record a screen capture so that I can understand the issue better? Or maybe provide steps to reproduce?

**Comment by headquarter8302** [comment] 2023-10-01 00:51
Steps:
1. Open the drawer, any drawer even. Including the filter drawer and the extra wallpaper information drawer.
2. Close it, either via dragging it down, using the back button, or by tapping a blank space.
3. Nothing else can be interacted with.

I've also attached a video example:

https://github.com/ammargitham/WallFlow/assets/65797058/3e7e62ef-a6e9-4a2e-ad1b-fa000576d952

**Comment by ammargitham** [comment] 2023-10-01 02:08
Hi, thanks for the screen recording. It seems, I didn't encounter this in debug builds. I can reproduce on a release build. Will look into it.

**Comment by ammargitham** [comment] 2023-10-01 02:37
Actually it was caused by an [Android library bug](https://android-review.googlesource.com/c/platform/frameworks/support/+/2745633). I already [updated to that version](https://github.com/ammargitham/WallFlow/blob/892bb42d1244f78448c658b34b684aff47a3aee6/gradle/libs.versions.toml#L10C34-L10C34), so will be fixed in the next release. Maybe tonight.

Fixed in d358b13f7f333c383031cc5424130a6633813835.

**Closed by ammargitham** 2023-10-01 02:37 UTC
Labels: bug

**Comment by ammargitham** [comment] 2023-10-01 11:06
Fixed in [v1.5.0](https://github.com/ammargitham/WallFlow/releases/tag/v1.5.0)
