### ISSUE TITLE
Reproducible build failed

### ISSUE THREAD

**Issue by linsui** [ammargitham/WallFlow#44] opened 2023-12-03 15:35 UTC
[com.ammar.wallflow.plus.zip](https://github.com/ammargitham/WallFlow/files/13539439/com.ammar.wallflow.plus.zip)

We have saw similiar issues on other apps. See https://gitlab.com/fdroid/fdroiddata/-/issues/3138.

**Comment by ammargitham** [comment] 2023-12-03 16:50
Hi. Thanks for the notification. I was aware of the failure and was trying to debug the cause the whole day. Will share my findings in the thread.

**Comment by ammargitham** [comment] 2023-12-17 14:40
Fixed in v2.2.1

**Closed by ammargitham** 2023-12-17 14:40 UTC
Labels: library bug
