### ISSUE TITLE
App crash when applying for wallpaper

### ISSUE THREAD

**Issue by Agi0m** [ammargitham/WallFlow#14] opened 2023-09-19 12:08 UTC
Version: 1.3.0
Android version: 13
Device: Samsung A14

When trying to apply wallpaper it show up to the set wallpaper then it crashes the app.

Tried to clear data and download the app again the same end result.

**Comment by ammargitham** [comment] 2023-09-19 12:55
Seems to be duplicate of #12

**Closed by ammargitham** 2023-09-19 12:55 UTC
